---
name: "Build nix flake"
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
  workflow_dispatch:  # allows manual triggering
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: cameronraysmith
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build -A checks.x86_64-linux
      - run: |
          scripts/push_image.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        if: github.ref == 'refs/heads/main'
